# Generated by Django 4.0.3 on 2022-04-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
